language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kanavdev46/dockerreact -f Dockerfile.dev .

script:
  - docker run kanavdev46/dockerreact npm run test -- --coverage

# -e CI=true